import Head from "next/head";
import { Inter } from "next/font/google";
import Header from "@/components/Header";
import CardDeck from "@/components/CardDeck";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>PANCRADogs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <CardDeck />
      <Footer />
    </>
  );
}
