import Head from 'next/head';
import { useEffect, useState } from "react";
import { Inter } from 'next/font/google';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import {faBone} from '@fortawesome/free-solid-svg-icons'
import Header from '@/components/Header/Header';
import Card from '@/components/Card/Card';
import Button from '@/components/Button/Button';
import Footer from '@/components/Footer/Footer';

import styles from "../styles/Home.module.scss";

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const [dogs, setDogs] = useState([]);

  useEffect(() => {
    const fetchData = async () => {
      try {
        const dogs = await fetch("/api/dogs")
          .then((res) => res.json())
        setDogs(dogs)
      } catch (err) {
        console.log(err);
      }
    }
    fetchData()
  }, [])

  return (
    <>
      <Head>
        <title>Next.js-DogAPI assignment</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        
      </Head>
      <div className={styles.home}>
     <Header/>
<main className={styles.mainContainer}>
     <section className={styles.topSection} >
     <FontAwesomeIcon icon={faBone} className={styles.homeIcon}/>
     <h2>Ten dog breeds with images</h2>
     </section>


<section className={styles.cardSection}>
     {dogs.slice(0, 10).map((dog, index) => {
      
                return <Card key={index} breedName={dog.breedName} breedImage={dog.breedImage}  />
              })}
</section>


      <section className={styles.bottomSection} >
      <h2>See more dogs? Click on my paw!</h2>
     <Button/>
     </section>
    </main>

     <Footer/>
     </div>


    </>
  )
}
