import React, { useState, useEffect } from 'react';
import Head from 'next/head';

export default function Dogs() {
    const [breeds, setBreeds] = useState([]);

    useEffect(() => {
        fetch('https://dog.ceo/api/breeds/list/all')
            .then(response => response.json())
            .then(data => {
                console.log("mensage");
                console.log(data.message);
                //selecciona las razas de perritos.
                const breeds = Object.keys(data.message)
                    //se utiliza el método sort con una función de comparación que devuelve un número aleatorio entre -0.5 y 0.5 para desordenar el arreglo de razas
                    .sort(() => Math.random() - 0.5)
                    //se utiliza el método slice para seleccionar las primeras 10 razas del arreglo desordenado.
                    .slice(0, 10);
                console.log(`breeds: ${typeof (breeds)}: ${breeds}`);
                //Promise.all espera que todas las solicitudes al API se completen y para obtener las URLs de las imágenes.
                return Promise.all(
                    breeds.map(breed =>
                        fetch(`https://dog.ceo/api/breed/${breed}/images/random`)
                            .then(response => response.json())
                            .then(data => ({ breed, image: data.message }))
                    )
                );
            })
            //.then(breeds => setBreeds(breeds));
            .then(breeds => {
                setBreeds(breeds);
                console.log("final breeds:")
                console.log(breeds);
            });
    }, []);

    return (
        <>
            <Head>
                <title>API Dogs</title>
                <meta name="description" content="Generated by Jorge Ardila" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className="container">
                <h1 className="my-5 text-center">Dog Breeds</h1>
                <div className="row row-cols-2">
                    {breeds.map(({ breed, image }) => (
                        <div key={breed} className="col mb-3">
                            <h2>{breed}</h2>
                            <img src={image} alt={breed} className="img-fluid dog-image" />
                        </div>
                    ))}
                </div>
            </div>
        </>
    );
}
