import GridLayout from '@/components/GridLayout/GridLayout'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Dog Breeds</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/ico.png" />
      </Head>
      <main>
        <h1>Dog Breeds</h1>
        <GridLayout/>
      </main>
    </>
  )
}
